name: ospcdyn
channels:
- ospc
dependencies:
- ipython
- ipython-notebook
- setuptools
- mkl
- scipy>=0.18.1
- matplotlib
- taxcalc>=0.12.0
- numba
- numpy>=1.12.1
- pandas>=0.20.1
- pytest
- python=2.7
