name: ogusa-dev
channels:
- PSLmodels
- conda-forge
dependencies:
- python>=3.7.7
- ipython
- setuptools
- mkl>=2020.2
- psutil
- scipy>=1.5.0
- pandas>=1.0.5
- matplotlib
- taxcalc>=3.0.0
- dask==2.30.0
- dask-core==2.30.0
- distributed==2.30.1
- paramtools>=0.15.0
- openpyxl
- sphinx>=3.1.2
- pip
- pytest>=6.0
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- requests
- xlwt
- pip:
  - jupyter-book==0.9.1
  - cs-kit
  - cs2tc
