name: ogcore-dev
channels:
- conda-forge
dependencies:
- python>=3.7.7, <3.12
- ipython
- setuptools
- scipy>=1.7.1
- pandas>=1.2.5
- matplotlib
- dask>=2.30.0
- dask-core>=2.30.0
- distributed>=2.30.1
- paramtools>=0.15.0
- pytest>=6.0
- pytest-xdist
- pylint
- coverage
- requests
- openpyxl
- black
- pip
- pip:
  - pygam

