name: ospcdyn
channels:
- ospc
dependencies:
- ipython
- ipython-notebook
- setuptools
- nomkl
- scipy=0.18.1
- matplotlib
- taxcalc=0.8.3
- numba
- numpy=1.11.2
- pandas==0.18.0
- pytest
- python=2.7
