name: ogusa-dev
channels:
- PSLmodels
- conda-forge
dependencies:
- python>=3.7.7
- ipython
- setuptools
- mkl
- psutil
- scipy>=1.5.0
- pandas>=1.0.5
- matplotlib
- taxcalc>=2.9.0
- dask>=2.20.0
- paramtools>=0.15.0
- openpyxl
- pip
- pytest>=6.0
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- requests
- xlwt
- pip:
  - cs-kit
  - xlrd
