name: Build and Deploy Jupyter Book documentation
on:
  push:
    branches:
      - master
    paths:
      - './docs/**.png'
      - './docs/book/content/theory/images/**.png'
      - './docs/book/**.yml'
      - './docs/book/**.bib'
      - '**.md'
      - './docs/book/content/api/**.rst'
      - './ogcore/**.py'
jobs:
  build-and-deploy:
    if: github.repository == 'PSLmodels/OG-Core'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: ogcore-dev
          environment-file: environment.yml
          python-version: "3.13"
          auto-activate-base: false

      - name: Build # Build Jupyter Book
        shell: bash -l {0}
        run: |
          pip install -e .
          python -m ipykernel install --user --name=ogcore-dev
          make build-docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/book/_build/html # The folder the action should deploy.
